=== geeksg/module-2/table.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definition of simple elements -->

	<xs:element name="fed_id" type="xs:integer" />
	<xs:element name="cust_id" type="xs:integer" />

	<!-- restrictions to elements -->

	<xs:element name="ve_no" type="xs:string" >
		<xs:simpleType>
			<xs:restriction base="string">
				<xs:pattern="[A-Z][0-9]">
			</xs:restriction>
		<xs:simpleType/>
	
	<xs:element name="ve_type" type="xs:string" />
	<xs:element name="se_da" type="xs:date" />
	<xs:element name="rat" type="xs:integer" />

	<!-- definition of complex elements -->

	<xs:element name="feedback">
	  	<xs:complexType>
			<xs:sequence>
				<xs:element ref="fed_id" />
				<xs:element ref="cust_id" />
				<xs:element ref="ve_no" />
				<xs:element ref="ve_type" />
				<xs:element ref="se_da" />
				<xs:element ref="rat" />
			</xs:sequence>	
		</xs:complexType>
	</xs:element>

	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="feedback" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== geeksg/module-2/table.xml
<?xml version="1.0" encoding="UtF-8"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="table.xsd">
	<feedback>
		<fed_id>3001</fed_id>
		<cust_id>2001</cust_id>
		<ve_no>TN 03 A1234</ve_no>
		<ve_type>Sedan</ve_type>
		<se_da>26-JUN-14</se_da>
		<rat>8</rat>
	</feedback>
	<feedback>
		<fed_id>3002</fed_id>
		<cust_id>2001</cust_id>
		<ve_no>KA 05 K3456</ve_no>
		<ve_type>HatchBack</ve_type>
		<se_da>13-MAY-14</se_da>
		<rat>7</rat>
	</feedback>
	<feedback>
		<fed_id>3003</fed_id>
		<cust_id>2002</cust_id>
		<ve_no>MA 15 M6789</ve_no>
		<ve_type>SmallCar</ve_type>
		<se_da>20-Feb-14</se_da>
		<rat>10</rat>
	</feedback>
	<feedback>
		<fed_id>3004</fed_id>
		<cust_id>2001</cust_id>
		<ve_no>TN 07 H4567</ve_no>
		<ve_type>Luxry</ve_type>
		<se_da>26-JUN-14</se_da>
		<rat>6</rat>
	</feedback>
	<feedback>
		<fed_id>3005</fed_id>
		<cust_id>2003</cust_id>
		<ve_no>KA 12 Y5567</ve_no>
		<ve_type>SUV</ve_type>
		<se_da>17-AUG-14</se_da>
		<rat>9</rat>
	</feedback>
	<feedback>
		<fed_id>3006</fed_id>
		<cust_id>2001</cust_id>
		<ve_no>KL 09 O8989</ve_no>
		<ve_type>Compact</ve_type>
		<se_da>10-JUL-14</se_da>
		<rat>4</rat>
	</feedback>	
</table>
